events {
    worker_connections 1024;
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;
    resolver 127.0.0.11 valid=30s;
}

http {
    upstream api {
        server api:8080;  # "api" = your Go service name in docker-compose
    }
    map $uri $image_ct {
          default        "";
          ~*\.jpe?g$     "image/jpeg";
          ~*\.png$       "image/png";
          ~*\.gif$       "image/gif";
          ~*\.webp$      "image/webp";
          ~*\.svg$       "image/svg+xml";
      }

    server {
        listen 80;
        server_name localhost;

        # API routes
        location /api/ {
            proxy_pass         http://api;
            proxy_http_version 1.1;

            # Pass real client info to Go app
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            # Timeouts — important for file uploads (cleaning photos)
            proxy_connect_timeout 60s;
            proxy_send_timeout    60s;
            proxy_read_timeout    60s;

            # Upload size — cleaners upload photos
            client_max_body_size 10M;
        }

        # Health check passthrough
        location /health {
            proxy_pass http://api;
        }

        # Block anything else
        location / {
            return 404;
        }

        location /uploads/ {
              try_files $uri @s3;
              root /var/www;
            }
            #aws s3
            location @s3 {
              rewrite ^/uploads/(.*)$ /ecommerce-uploads/$1 break;
              proxy_pass http://localstack:4566;
              proxy_set_header Host $host;

              # Remove download headers
               proxy_hide_header Content-Disposition;
               add_header Content-Disposition "inline" always;

               proxy_hide_header Content-Type;
                if ($image_ct != "") {
                    add_header Content-Type $image_ct always;
                }
            }
          }
    }
}